import { useState } from 'react';
import { motion } from 'framer-motion';

interface WireframeScreen {
  name: string;
  description: string;
}

interface PenpotPreviewProps {
  /** Penpot share URL — nếu có sẽ embed trực tiếp qua iframe */
  penpotUrl?: string;
  /** Title của thiết kế */
  title?: string;
  /** Static wireframe image URL hoặc path (fallback khi chưa có Penpot) */
  wireframeImageUrl?: string;
  /** Mô tả ngắn về thiết kế */
  description?: string;
  /** Số màn hình trong thiết kế */
  screenCount?: number;
  /** Số component trong thiết kế */
  componentCount?: number;
  /** Danh sách màn hình */
  screens?: WireframeScreen[];
  /** Summary của UX flow */
  flowSummary?: string;
}

const DEFAULT_SCREENS: WireframeScreen[] = [
  { name: 'Dashboard', description: 'Pipeline overview & phase status' },
  { name: 'Artifact Viewer', description: 'Browse & review agent outputs' },
  { name: 'HITL Gate', description: 'Approve / Reject / Request Changes' },
  { name: 'Audit Trail', description: 'Timeline & history sidebar' },
];

/**
 * PenpotPreview — Fallback-first Design Preview Component
 *
 * Behaviour:
 * - Nếu `penpotUrl` được truyền → embed Penpot viewer qua iframe
 * - Nếu không → render static wireframe + metadata card (fallback)
 *
 * Để tích hợp Penpot sau: chỉ cần truyền prop `penpotUrl`, không sửa code.
 */
export default function PenpotPreview({
  penpotUrl,
  title = 'UI/UX Design',
  wireframeImageUrl,
  description = 'Wireframe & screen specification generated by UX Agent.',
  screenCount,
  componentCount,
  screens = DEFAULT_SCREENS,
  flowSummary,
}: PenpotPreviewProps) {
  const [iframeError, setIframeError] = useState(false);
  const [activeScreen, setActiveScreen] = useState(0);

  // --- Penpot iframe mode ---
  if (penpotUrl && !iframeError) {
    return (
      <div className="penpot-preview penpot-preview--iframe">
        <div className="penpot-iframe-header">
          <span className="penpot-iframe-icon">🎨</span>
          <span className="penpot-iframe-title">{title}</span>
          <a
            href={penpotUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="penpot-open-btn"
          >
            Open in Penpot ↗
          </a>
        </div>
        <iframe
          src={penpotUrl}
          className="penpot-iframe"
          title={title}
          onError={() => setIframeError(true)}
          allow="fullscreen"
        />
      </div>
    );
  }

  // --- Fallback: Static wireframe + metadata card ---
  return (
    <motion.div
      className="penpot-preview penpot-preview--fallback"
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
    >
      {/* Header */}
      <div className="penpot-header">
        <div className="penpot-header-left">
          <span className="penpot-icon">🖼️</span>
          <div>
            <div className="penpot-title">{title}</div>
            <div className="penpot-subtitle">Wireframe Preview</div>
          </div>
        </div>
        <div className="penpot-penpot-badge">
          <span className="penpot-badge-dot" />
          Penpot: Setup pending
        </div>
      </div>

      {/* Main content: Image + Screens list */}
      <div className="penpot-body">
        {/* Left: wireframe image or placeholder */}
        <div className="penpot-image-pane">
          {wireframeImageUrl ? (
            <img
              src={wireframeImageUrl}
              alt={`${title} wireframe`}
              className="penpot-wireframe-img"
            />
          ) : (
            <div className="penpot-wireframe-placeholder">
              <div className="penpot-wf-grid">
                {/* Simulated wireframe grid */}
                <div className="penpot-wf-topbar" />
                <div className="penpot-wf-sidebar" />
                <div className="penpot-wf-main">
                  <div className="penpot-wf-card" />
                  <div className="penpot-wf-card" />
                  <div className="penpot-wf-card" />
                </div>
                <div className="penpot-wf-bottom" />
              </div>
              <div className="penpot-wf-label">
                <span>Wireframe Preview</span>
                <span className="penpot-wf-hint">Connect Penpot for live design</span>
              </div>
            </div>
          )}
        </div>

        {/* Right: metadata */}
        <div className="penpot-meta-pane">
          {/* Stats */}
          <div className="penpot-stats">
            <div className="penpot-stat">
              <div className="penpot-stat-value">{screenCount ?? screens.length}</div>
              <div className="penpot-stat-label">Screens</div>
            </div>
            <div className="penpot-stat">
              <div className="penpot-stat-value">{componentCount ?? '—'}</div>
              <div className="penpot-stat-label">Components</div>
            </div>
            <div className="penpot-stat">
              <div className="penpot-stat-value">v1</div>
              <div className="penpot-stat-label">Version</div>
            </div>
          </div>

          {/* Description */}
          {description && (
            <p className="penpot-description">{description}</p>
          )}

          {/* Flow Summary */}
          {flowSummary && (
            <div className="penpot-flow-summary">
              <div className="penpot-flow-label">UX Flow Summary</div>
              <p className="penpot-flow-text">{flowSummary}</p>
            </div>
          )}

          {/* Screen list */}
          <div className="penpot-screens">
            <div className="penpot-screens-label">Screen Index</div>
            {screens.map((screen, idx) => (
              <button
                key={idx}
                className={`penpot-screen-item ${activeScreen === idx ? 'penpot-screen-item--active' : ''}`}
                onClick={() => setActiveScreen(idx)}
              >
                <span className="penpot-screen-num">{String(idx + 1).padStart(2, '0')}</span>
                <div>
                  <div className="penpot-screen-name">{screen.name}</div>
                  <div className="penpot-screen-desc">{screen.description}</div>
                </div>
              </button>
            ))}
          </div>

          {/* Penpot integration CTA */}
          <div className="penpot-cta">
            <span className="penpot-cta-icon">🔗</span>
            <div>
              <div className="penpot-cta-title">Connect Penpot</div>
              <div className="penpot-cta-desc">
                Set <code>PENPOT_SHARE_URL</code> in backend env to enable live design preview
              </div>
            </div>
          </div>
        </div>
      </div>
    </motion.div>
  );
}
