// Backend composition root.
//
// Beginner reading guide: this file wires middleware/routes and performs boot
// recovery. Business workflow logic belongs in SdlcWorkflowService, while task
// lifecycle and gate recovery belong to their dedicated services.

const path = require('path');
const express = require('express');
const cors = require('cors');
const { PORT, NODE_ENV, FRONTEND_URL } = require('./config/environment');
const prisma = require('./config/database');
const routes = require('./routes');
const { startBatchJobs } = require('./jobs/batchJob');
const { errorHandler, notFoundHandler } = require('./middleware/errorHandler');
const { requestLogger } = require('./middleware/logger');
const { requestContextMiddleware } = require('./middleware/requestContext');
const gateBridge = require('./services/gateBridge');
const taskWorker = require('./services/taskWorkerService');
const SdlcWorkflowService = require('./services/SdlcWorkflowService');

const Sentry = require('@sentry/node');
const { nodeProfilingIntegration } = require('@sentry/profiling-node');

Sentry.init({
  dsn: process.env.SENTRY_DSN || '',
  integrations: [
    nodeProfilingIntegration(),
  ],
  tracesSampleRate: 1.0,
  profilesSampleRate: 1.0,
});

const app = express();
const PRISMA_CONNECT_TIMEOUT_MS = 5_000;
const originalAppListen = app.listen.bind(app);

if (NODE_ENV === 'test') {
  app.listen = (...args) => {
    const nextArgs = [...args];
    if (typeof nextArgs[0] === 'number' && nextArgs.length === 1) {
      nextArgs.splice(1, 0, '127.0.0.1');
    } else if (typeof nextArgs[0] === 'number' && typeof nextArgs[1] === 'function') {
      nextArgs.splice(1, 0, '127.0.0.1');
    }
    return originalAppListen(...nextArgs);
  };
}

const connectPrismaWithTimeout = () => Promise.race([
  prisma.$connect(),
  new Promise((_, reject) => {
    setTimeout(
      () => reject(new Error(`Timed out after ${PRISMA_CONNECT_TIMEOUT_MS}ms`)),
      PRISMA_CONNECT_TIMEOUT_MS
    );
  }),
]);

// CORS configuration
const allowedOrigins = new Set(
  FRONTEND_URL
    .split(',')
    .map((origin) => origin.trim())
    .filter(Boolean)
);

if (NODE_ENV !== 'production') {
  allowedOrigins.add('http://localhost:5173');
  allowedOrigins.add('http://localhost:3000');
}

const corsConfig = {
  origin(origin, callback) {
    const isLocalDevOrigin = NODE_ENV !== 'production'
      && /^http:\/\/(localhost|127\.0\.0\.1):\d+$/.test(origin || '');
    if (!origin || allowedOrigins.has(origin) || isLocalDevOrigin) {
      return callback(null, true);
    }
    return callback(new Error(`Origin ${origin} is not allowed by CORS`));
  },
  credentials: true,
};

app.use(cors(corsConfig));
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ extended: true }));

// Assign a request id before request logging/routes so logs and errors correlate.
app.use(requestContextMiddleware);

if (NODE_ENV === 'development') {
  app.use(requestLogger);
}

// Health check
app.get('/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// Static UX preview files (SVG wireframes generated by the UX agent)
app.use('/ux-previews', express.static(path.join(__dirname, '../../public/ux-previews'), {
  setHeaders(res) { res.setHeader('Cache-Control', 'no-store'); },
}));

// Serve uploaded files statically
app.use('/uploads', express.static(path.join(__dirname, '../uploads')));

// API routes
app.use('/api/v1', routes);

// Error handling
app.use(notFoundHandler);
app.use(errorHandler);

// Start server
const startServer = async () => {
  try {
    // Test Prisma connection
    try {
      await connectPrismaWithTimeout();
      console.log('[Prisma] Connection verified.');
      const interrupted = await gateBridge.markOrphanedPendingInterrupted();
      if (interrupted.count > 0) {
        console.warn(`[GateBridge] Marked ${interrupted.count} orphaned pending gate(s) as interrupted.`);
      }
      // Reclaim tasks left running by a crashed process, then keep sweeping.
      const reclaimed = await taskWorker.sweepStale({ reason: 'orphaned by backend restart' });
      if (reclaimed > 0) {
        console.warn(`[TaskWorker] Reclaimed ${reclaimed} orphaned running task(s) on boot.`);
      }
      taskWorker.startSweeper();
      // Re-dispatch only stages whose live gate continuation was lost on restart.
      const resumed = await SdlcWorkflowService.recoverInterruptedGates();
      if (resumed > 0) {
        console.warn(`[Recovery] Re-dispatched ${resumed} interrupted-gate stage(s).`);
      }
    } catch (dbError) {
      console.error('[Prisma] Connection test failed:', dbError.message);
      console.warn('[Prisma] Ensure database exists and schema is pushed');
    }

    // Start listening
    const server = app.listen(PORT, () => {
      console.log(`[Server] Backend running on http://localhost:${PORT}`);
      console.log(`[Server] Environment: ${NODE_ENV}`);
      console.log(`[Server] Agents URL: ${process.env.AGENTS_BASE_URL || 'http://127.0.0.1:8001'}`);
      startBatchJobs();
    });
  } catch (error) {
    console.error('[Server] Failed to start:', error);
    process.exit(1);
  }
};

// T4/I7: process-level safety net, behaviour split by environment.
// - dev/demo: keep the server alive so a single bad request/agent run does not
//   end the demo.
// - production: the process state is undefined after an uncaught exception, so
//   serving further requests is unsafe. Log and exit non-zero; the supervisor
//   (Docker/PM2/k8s) restarts a clean process.
const isProduction = () => NODE_ENV === 'production';

process.on('unhandledRejection', (reason) => {
  Sentry.captureException(reason);
  console.error('[Process] Unhandled promise rejection:', reason);
  if (isProduction()) {
    Sentry.flush(2000).then(() => process.exit(1));
  }
});
process.on('uncaughtException', (err) => {
  Sentry.captureException(err);
  console.error('[Process] Uncaught exception:', err);
  if (isProduction()) {
    Sentry.flush(2000).then(() => process.exit(1));
  }
});

if (require.main === module) {
  startServer();
}

module.exports = app;
